spring:
  profiles.active: dev

--- #development profile = dev

spring:
  profiles: dev

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    schema: classpath:sql/init-schema.sql
    data: classpath:sql/populate-data.sql

  h2:
    console:
      enabled: true

jwt:
  client-secret: eJFwX4l5lDKwITxGnxWIoDTjqJ4HHO0bkGRNwf5d0jHNPpABi3wMkivDBtDSaH6sYoStXihjPx10PjcxfT9v9w==
  access-token-validitity-seconds: 1800

server:
  port: 5000
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store: classpath:ssl/miw_task_java.p12
    key-store-password: miwtaskjava
    key-alias: miwtaskjava

logging:
  file:
    name: logs/miw-task-java.log
